# Copyright 2026 Rahul Kashyap (Indian Institute of Technology Bombay)
# SPDX-License-Identifier: Apache-2.0 -- see LICENSE and NOTICE (attribution required)
"""Check that arch/model.yaml, the code and the docs agree.

    python arch/check_drift.py                 # rkdev / any branch
    python arch/check_drift.py --branch main   # also forbids rkdev-only paths

Exit code 1 if any FAIL. Every message names the rule, where it was found and how to fix it. The report is also
written to docs/_generated/arch/drift_report.md for the Architecture page.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import extract as X  # noqa: E402

ROOT = X.ROOT
EDGE_TYPES = ("uses", "requires", "reads", "registers")
# Paths that must never exist on `main` (rkdev-only material; see the rkdev docs). Path names only.
MAIN_FORBIDDEN = ["CLAUDE.md", ".rkdev-only", "docs/rkdev", "docs/roadmap/plans", "scripts/promote_to_main.sh"]

_MD_LABEL = [re.compile(r"^\(([\w:.\-]+)\)=", re.M), re.compile(r"^\s*:name:\s*([\w:.\-]+)", re.M),
             re.compile(r"\$\$\s*\(([\w:.\-]+)\)")]
_PY_LABEL = re.compile(r"\$\$\s*\(([\w:.\-]+)\)")
_CITE = re.compile(r"(?:\{eq\}|:eq:)`([\w:.\-]+)`")


class Report:
    def __init__(self):
        self.fails, self.warns = [], []

    def fail(self, rule, where, msg, fix):
        self.fails.append((rule, where, msg, fix))

    def warn(self, rule, where, msg, fix):
        self.warns.append((rule, where, msg, fix))

    def markdown(self):
        lines = ["```{table} Architecture drift check.", ":name: tab-drift-report", "",
                 "| level | rule | where | problem | fix |", "|---|---|---|---|---|"]
        esc = lambda s: str(s).replace("|", "\\|")  # noqa: E731
        for lvl, items in (("FAIL", self.fails), ("warn", self.warns)):
            lines += [f"| {lvl} | {esc(r)} | `{esc(w)}` | {esc(m)} | {esc(f)} |" for r, w, m, f in items]
        if not (self.fails or self.warns):
            lines.append("| ok | all rules | — | model, code and docs agree | — |")
        return "\n".join(lines + ["```", ""])

    def print(self):
        for lvl, items in (("FAIL", self.fails), ("warn", self.warns)):
            for r, w, m, f in items:
                print(f"{lvl:4s} [{r}] {w}: {m}\n       fix: {f}")
        print(f"\n{len(self.fails)} failure(s), {len(self.warns)} warning(s)")


# --------------------------------------------------------------------------- label index
def generated_labels():
    """Labels defined by snippets the docs build generates (absent in a fresh checkout).

    Taken from the same registries the generators use, so they cannot drift:
    scripts/make_doc_figures.FIGURES (figures + settings tables) and arch/render.py (views, workflows, tables).
    """
    out = {}
    try:
        sys.path.insert(0, os.path.join(ROOT, "scripts"))
        import make_doc_figures as mdf

        for name, fig in mdf.FIGURES.items():
            out[fig["label"]] = f"generated by scripts/make_doc_figures.py ({name})"
            out[f"tab-settings-{name.replace('_', '-')}"] = "generated by scripts/make_doc_figures.py"
    except Exception:  # noqa: BLE001
        pass
    model = X.load_model()
    for view in model.get("views", {}):
        out[f"fig-arch-{view}"] = "generated by arch/render.py"
    for par in glob.glob(os.path.join(ROOT, "par", "*.par")):
        n = os.path.basename(par)[:-4].replace("_", "-")
        for lab in (f"fig-workflow-{n}", f"tab-schedule-{n}", f"tab-settings-run-{n}", f"sec-workflow-{n}"):
            out[lab] = "generated by arch/render.py"
    for lab in ("tab-arch-components", "tab-problem-thorns", "tab-problem-cost", "tab-drift-report"):
        out[lab] = "generated by arch/render.py"
    return out


def label_index():
    """label -> file that defines it (docs Markdown, docstrings, and build-generated snippets)."""
    labels = dict(generated_labels())
    for f in glob.glob(os.path.join(ROOT, "docs", "**", "*.md"), recursive=True):
        if "_build" in f:
            continue
        with open(f) as fh:
            text = fh.read()
        for rx in _MD_LABEL:
            for m in rx.finditer(text):
                labels.setdefault(m.group(1), os.path.relpath(f, ROOT))
    for f in X.python_files():
        with open(os.path.join(ROOT, f)) as fh:
            for m in _PY_LABEL.finditer(fh.read()):
                labels.setdefault(m.group(1), f)
    return labels


def citations():
    cited = set()
    files = glob.glob(os.path.join(ROOT, "docs", "**", "*.md"), recursive=True) + \
        [os.path.join(ROOT, f) for f in X.python_files()] + [os.path.join(ROOT, "scripts", "make_doc_figures.py")]
    for f in files:
        if "_build" in f or not os.path.exists(f):
            continue
        with open(f) as fh:
            cited |= set(_CITE.findall(fh.read()))
    return cited


# --------------------------------------------------------------------------- checks
def check_pointers(model, rep, labels):
    for name, c in model["components"].items():
        for s in c.get("src", []):
            if not X._exists_exact(s.rstrip("/")):
                rep.fail("pointer", f"{name}.src", f"`{s}` does not exist", "update `src:` after the move/rename")
        if c.get("doc") and not os.path.exists(os.path.join(ROOT, c["doc"])):
            rep.fail("pointer", f"{name}.doc", f"`{c['doc']}` does not exist", "fix `doc:`")
        if c.get("notes"):
            path, _, label = c["notes"].partition("#")
            if not os.path.exists(os.path.join(ROOT, path)):
                rep.fail("pointer", f"{name}.notes", f"`{path}` does not exist", "fix `notes:`")
            elif label and label not in labels:
                rep.fail("pointer", f"{name}.notes", f"label `{label}` is not defined",
                         "fix `notes:` or restore the label")
        for eq in c.get("equations", []):
            if eq not in labels:
                rep.fail("pointer", f"{name}.equations", f"equation label `{eq}` is not defined",
                         "label the equation `$$ … $$ (" + eq + ")` or fix `equations:`")


def check_coverage(model, ext, rep):
    for f, comp in ext["modules"].items():
        if comp not in model["components"]:
            rep.fail("coverage", f, f"module is mapped to unknown component `{comp}`",
                     "fix the `# @component:` tag or the component name")
    for f in X.python_files():
        if f not in ext["modules"]:
            rep.fail("coverage", f, "module belongs to no component",
                     "add it to a component's `src:` in arch/model.yaml (or a new component)")
    claimed = {t.lower() for c in model["components"].values() for t in c.get("thorns", [])}
    for t, info in ext["thorns"].items():
        if t.lower() not in claimed:
            rep.fail("coverage", info["module"], f"thorn `{t}` is claimed by no component",
                     "list it under `thorns:` of its component")


def _curated_edges(model):
    out = {t: set() for t in EDGE_TYPES}
    for name, c in model["components"].items():
        for t in ("uses", "requires", "reads"):
            for b in c.get(t, []):
                out[t].add((name, b))
        for r in c.get("registers", []):
            out["registers"].add((name, r["into"], r.get("stage"), tuple(sorted(r.get("functions", [])))))
    return out


def _extracted_edges(ext):
    out = {t: {} for t in EDGE_TYPES}
    for e in ext["edges"]:
        if e["type"] == "registers":
            key = (e["from"], e["to"], e["stage"], tuple(sorted(x for x in e["functions"] if x)))
        else:
            key = (e["from"], e["to"])
        out[e["type"]].setdefault(key, e)
    # merge registrations of the same (from, into, stage) made by several calls
    merged = {}
    for (a, b, st, fns), e in out["registers"].items():
        k = (a, b, st)
        prev = merged.get(k)
        merged[k] = (tuple(sorted(set(fns) | set(prev[0] if prev else ()))), e)
    out["registers"] = {(a, b, st, fns): e for (a, b, st), (fns, e) in merged.items()}
    return out


def check_edges(model, ext, rep):
    cur, exe = _curated_edges(model), _extracted_edges(ext)
    comps = model["components"]
    for t in EDGE_TYPES:
        for key, e in exe[t].items():
            if key in cur[t]:
                continue
            a, b = key[0], key[1]
            where = f"{e['file']}:{e['line']}"
            if t == "registers":
                rep.fail("edge", where, f"`{a}` registers {', '.join(key[3])} into `{b}` [{key[2]}] "
                         f"({e['detail']}), not recorded", f"add `{{into: {b}, stage: {key[2]}, functions: "
                         f"[{', '.join(key[3])}]}}` to `{a}.registers`")
            else:
                hint = " (or `requires`)" if t == "reads" else ""
                rep.fail("edge", where, f"`{a}` {t} `{b}` ({e['detail']}) but `{a}.{t}` lacks it",
                         f"add `{b}` to `{a}.{t}`{hint}" if a in comps else f"map `{a}` to a component")
        for key in cur[t]:
            if key not in exe[t]:
                rep.warn("edge", f"arch/model.yaml: {key[0]}.{t}",
                         f"`{key[0]}` {t} `{key[1]}` has no evidence in the code",
                         f"remove it from `{key[0]}.{t}`, or the code no longer does it")


def check_layers(model, ext, rep):
    comps, allowed = model["components"], model["layers"]["allowed_uses"]
    for e in ext["edges"]:
        if e["type"] != "uses" or e["from"] not in comps or e["to"] not in comps:
            continue
        la, lb = comps[e["from"]].get("layer"), comps[e["to"]].get("layer")
        if lb != "external" and lb not in allowed.get(la, []):
            rep.fail("layer", f"{e['file']}:{e['line']}",
                     f"`{e['from']}` ({la}) uses `{e['to']}` ({lb}); {la} may only use {allowed.get(la)}",
                     "move the code to the right layer, or go through flesh hooks / backends")


def check_flows(model, ext, rep):
    probs = ext.get("problems", {})
    if not probs:
        return
    gfs = {g.lower() for p in probs.values() for g in p["gridfunctions"] + p["groups"]}
    comps = model["components"]
    thorn_comp = {t.lower(): n for n, c in comps.items() for t in c.get("thorns", [])}
    regs_into = {n: {r["into"] for r in c.get("registers", [])} for n, c in comps.items()}
    for i, f in enumerate(model.get("flows", [])):
        where = f"flows[{i}] {f['from']} → {f['to']}"
        for d in f.get("data", []):
            if "::" in d and d.lower() not in gfs:
                rep.fail("flow", where, f"grid function/group `{d}` is not registered in any par-file run",
                         "fix the name (Thorn::var or Thorn::group)")
        st = f.get("stage")
        if st == "on demand" or comps.get(f["from"], {}).get("layer") == "external" \
                or comps.get(f["to"], {}).get("layer") == "external":
            continue
        ends = {f["from"], f["to"]}
        ends |= regs_into.get(f["from"], set()) | regs_into.get(f["to"], set())
        ok = False
        for p in probs.values():
            for item in p["schedule"].get(st, []):
                if thorn_comp.get(item.split("::")[0].lower()) in ends:
                    ok = True
        if not ok:
            rep.fail("flow", where, f"no routine of these components runs in `{st}` in any problem",
                     "fix `stage:` (schedule bin) or the endpoints")


def check_problems(model, ext, rep):
    claimed = {t.lower() for c in model["components"].values() for t in c.get("thorns", [])}
    pages = {}
    for f in glob.glob(os.path.join(ROOT, "docs", "problems", "*.md")):
        with open(f) as fh:
            pages[os.path.relpath(f, ROOT)] = fh.read()
    for name, p in ext.get("problems", {}).items():
        if not any(f"workflow_{name}.md" in text for text in pages.values()):
            rep.fail("problem", p["parfile"], "no problem page includes its workflow snippet",
                     f"add ```{{include}} ../_generated/arch/workflow_{name}.md``` to its page in docs/problems/")
        for t in p["active_thorns"]:
            if t.lower() not in claimed:
                rep.fail("problem", p["parfile"], f"activates thorn `{t}` claimed by no component",
                         "add it to arch/model.yaml")


def check_docs(model, rep, labels, cited):
    api_text = ""
    for f in glob.glob(os.path.join(ROOT, "docs", "**", "*.md"), recursive=True):
        if "_build" not in f:
            with open(f) as fh:
                api_text += fh.read()
    for name, c in model["components"].items():
        if c.get("layer") == "external":
            continue
        mods = [s[:-3].replace("/", ".").removesuffix(".__init__") for s in c.get("src", []) if s.endswith(".py")]
        if mods and not any(re.search(rf"auto(module|function|class|summary)::?\s*{re.escape(m)}\b", api_text)
                            or f"{m}" in api_text for m in mods):
            rep.warn("docs", name, "no documentation page refers to its modules",
                     "add an automodule/autofunction or a :mod: reference")
    eqs = sorted({eq for c in model["components"].values() for eq in c.get("equations", [])})
    for eq in eqs:
        if eq in labels and eq not in cited:
            rep.warn("docs", eq, "equation label is never cited", "cite it with Eq. {eq}`" + eq + "`")


def check_readme(rep):
    try:
        import render
    except Exception as err:  # noqa: BLE001
        rep.warn("readme", "README.md", f"cannot import arch/render.py ({err})", "fix arch/render.py")
        return
    with open(os.path.join(ROOT, "README.md")) as fh:
        text = fh.read()
    m = re.search(r"<!-- arch:begin -->\n(.*?)<!-- arch:end -->", text, re.S)
    if not m:
        rep.fail("readme", "README.md", "architecture marker block missing",
                 "run `python arch/render.py --readme`")
    elif m.group(1) != render.readme_block():
        rep.fail("readme", "README.md", "architecture diagram block is stale",
                 "run `python arch/render.py --readme` and commit README.md")


def check_plans(rep):
    idx = os.path.join(ROOT, "docs", "roadmap", "index.md")
    if not os.path.exists(idx):
        return
    with open(idx) as fh:
        for line in fh:
            m = re.match(r"\|\s*`([\w-]+)`\s*\|\s*(\d{4}-\d{2}-\d{2})\s*\|[^|]*\|\s*([^|]*)\|", line)
            if m and "in progress" in m.group(3):
                age = (_dt.date.today() - _dt.date.fromisoformat(m.group(2))).days
                if age > 60:
                    rep.warn("roadmap", f"plan {m.group(1)}", f"in progress for {age} days",
                             "update its status in docs/roadmap/index.md")


def check_branch(branch, rep):
    if branch != "main":
        return
    for p in MAIN_FORBIDDEN:
        if os.path.exists(os.path.join(ROOT, p)):
            rep.fail("branch", p, "rkdev-only path present on main",
                     "never commit on main; main is updated only by promotion from rkdev")


def run(branch=None, write_report=True):
    rep = Report()
    model = X.load_model()
    ext = X.extract(model)
    X.write(ext)
    labels = label_index()
    check_pointers(model, rep, labels)
    check_coverage(model, ext, rep)
    check_edges(model, ext, rep)
    check_layers(model, ext, rep)
    check_flows(model, ext, rep)
    check_problems(model, ext, rep)
    check_docs(model, rep, labels, citations())
    check_readme(rep)
    check_plans(rep)
    check_branch(branch, rep)
    if write_report:
        os.makedirs(X.GEN, exist_ok=True)
        with open(os.path.join(X.GEN, "drift_report.md"), "w") as fh:
            fh.write(rep.markdown())
    return rep


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--branch", help="branch being checked (main forbids rkdev-only paths)")
    args = ap.parse_args()
    rep = run(args.branch)
    rep.print()
    sys.exit(1 if rep.fails else 0)


if __name__ == "__main__":
    main()
